### ISSUE TITLE
Unable to runon OSX

### ISSUE THREAD

**Issue by usmanismail** [ClusterHQ/flocker#1168]
I am following the tutorial and when I try run ```flocker-deploy deployment-node1.yml fig.yml``` I get the following error. 

main function encountered error
	Traceback (most recent call last):
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
	    self.__bootstrap_inner()
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
	    self.run()
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
	    self.__target(*self.__args, **self.__kwargs)
	--- <exception caught here> ---
	  File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
	    result = context.call(ctx, function, *args, **kwargs)
	  File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python

**Comment by lukemarsden** [comment]
@usmanismail That doesn't look like a complete traceback, could you try again to paste the whole thing please?

**Comment by exarkun** [comment]
Hi.  Thanks for your interest in Flocker.  It looks like the error report (the Python traceback) in the description has been truncated.  Can you provide the complete traceback as well as the contents of the two yml files you're using?  Thanks.

**Comment by usmanismail** [comment]
deployment-node1.yml

    "version": 1
	"nodes":
	  "192.168.128.158": ["web", "redis"]

fig.yml

	web:
	  image: clusterhq/flask
	  links:
	   - "redis:redis"
	  ports:
	   - "80:80"
	redis:
	  image: dockerfile/redis
	  ports:
	   - "6379:6379"
	  volumes: ["/data"]

Full Log Output

    flocker-deploy deployment-node1.yml fig.yml
    bash: flocker-reportstate: command not found
    main function encountered error
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
        self.__bootstrap_inner()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
    --- <exception caught here> ---
      File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
        result = context.call(ctx, function, *args, **kwargs)
      File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/lib/python2.7/site-packages/flocker/common/_ipc.py", line 90, in get_output
        raise IOError("Bad exit", remote_command, e.returncode, e.output)
    exceptions.IOError: ('Bad exit', ['flocker-reportstate'], 127, '')

**Comment by lukemarsden** [comment]
@usmanismail Thanks for the debug output! What is running on `192.168.128.158` and what steps did you take to configure that node for usage as part of a Flocker cluster?

**Comment by usmanismail** [comment]
Just docker on a ubuntu server, the tutorial does not mention any install
steps for target servers.
Are there docs for what needs to be setup there.

**Comment by lukemarsden** [comment]
Thanks for the feedback on the tutorial!

Please note the right hand side of the tutorial at https://docs.clusterhq.com/en/0.3.2/gettingstarted/ indicates that you should choose to deploy either using Vagrant or AWS. For more detailed install instructions, see here: https://docs.clusterhq.com/en/0.3.2/indepth/installation.html#installing-flocker-node

We are aware of this usability issue with the docs and are actively working to improve them :) See https://clusterhq.atlassian.net/browse/FLOC-1326
