### ISSUE TITLE
need inputs for the cluser IP in deployment-node1.yml

### ISSUE THREAD

**Issue by noah8713** [ClusterHQ/flocker#1180]
Hello 
I am testing the flocker tutorial on my OSX . Running 
flocker-deploy deployment-node1.yml fig.yml gives error below

```
Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 781, in __bootstrap
    self.__bootstrap_inner()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
--- <exception caught here> ---
  File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/vendor/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/lib/python2.7/site-packages/flocker/cli/_sshconfig.py", line 144, in configure_ssh
    host, commands.encode("ascii")])
  File "/usr/local/Cellar/flocker-0.3.2/0.3.2/libexec/lib/python2.7/site-packages/flocker/cli/_sshconfig.py", line 29, in ssh
    check_output([b"ssh"] + argv, stderr=STDOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
```

Can you please suggest, what DEMO IPs should work?

**Comment by binocarlos** [comment]
Hey - could I check which exact sequence of command you used to arrive at this error.

Mainly - I need to know if you brought up the 2 vagrant nodes (with a `vagrant up` command).

As much information as possible is useful :-)

Thanks!

**Comment by noah8713** [comment]
@binocarlos I am following the basic tutorial guide

https://docs.clusterhq.com/en/0.3.2/gettingstarted/index.html
I get error at step2 . I changed the container deploment path to localhost also which did not help instead of 172.**

**Comment by noah8713** [comment]
Its working now. Was problem in getting up one of the node. Rebooted my mac and again followed the same steps and it worked error free.

**Comment by noah8713** [comment]
Sorry for the steps part,  I skipped the cluster set up part using vagrant .Just followed the brew function ,cloned repository and entered the redis IP as localhost  which gave the above error. Hope it helps. Ideally it should work on local host
