### ISSUE TITLE
Flocker Cinder integration got issue: UnattachedVolume

### ISSUE THREAD

**Issue by CBR09** [ClusterHQ/flocker#2756]
Hi,
I've installed flocker with cinder backend following https://docs.clusterhq.com/en/latest/docker-integration/manual-install.html#installing-flocker-with-docker, but I got issue from dataset agent:

> {"exception": "flocker.node.agents.blockdevice.UnattachedVolume", "task_level": [2, 2, 5], "action_type": "flocker:agent:discovery", "reason": "74786f94-e812-4432-b454-6e0a3d85c437", "timestamp": 1460433422.225398, "task_uuid": "45716477-7f80-414c-b77c-3171d69561ae", "action_status": "failed"}
> {"exception": "flocker.node.agents.blockdevice.UnattachedVolume", "reason": "74786f94-e812-4432-b454-6e0a3d85c437", "timestamp": 1460433422.225944, "traceback": "Traceback: <class 'flocker.node.agents.blockdevice.UnattachedVolume'>: 74786f94-e812-4432-b454-6e0a3d85c437\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py:102:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:534:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:592:output\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py:529:output_CONVERGE\n--- <exception caught here> ---\n/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1798:discover_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1345:_count_calls\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1764:_discover_raw_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:2032:get_device_path\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py:686:get_device_path\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py:638:_get_device_path_virtio_blk\n", "message_type": "eliot:traceback", "task_uuid": "45716477-7f80-414c-b77c-3171d69561ae", "task_level": [2, 3]}
>  

My env:
OS: ubuntu 14.04
Agent.yml:

> "version": 1
> "control-service":
>    "hostname": "..."
>    "port": 4524
> dataset:
>  backend: "openstack"
>  auth_plugin: "password"
>  auth_url: "http://..../v3"
>  region: "..."
>  username: "..."
>  project_name: "...."
>  password: "...."
>  user_domain_name: "default"
>  project_domain_name: "default"

I also attached flocker-diagnostics tar to fully logs.
[clusterhq_flocker_logs_a59aaeb2-0062-11e6-8636-fa163e3cbcf2.tar.zip](https://github.com/ClusterHQ/flocker/files/214296/clusterhq_flocker_logs_a59aaeb2-0062-11e6-8636-fa163e3cbcf2.tar.zip)

If you need any information, please tell me know.

Thanks

**Comment by wallnerryan** [comment]
Thanks for the logs, will look into these. 

What version of Flocker are you using?

What openstack version are you using?

Thanks

**Comment by CBR09** [comment]
Hi @wallnerryan 
I give you some info that you need
> Flocker version:
> root@ubuntu1:~# flocker --version
> 1.11.0
> OpenStack version liberty

Thanks

**Comment by wallnerryan** [comment]
Thanks @CBR09 will look into this soon.

**Comment by CBR09** [comment]
Thanks @wallnerryan, Do you have any update on it?, or any suggestion for me to make flocker + cinder + flocker-docker-plugin work?.

**Comment by wallnerryan** [comment]
@CBR09 looks like `attach_volume` is failing. From the logs it looks like the volume cannot get attached, are you able to attach volumes to the VM the dataset agent is running on manually?

**Comment by CBR09** [comment]
Yes, I can, I run all flocker components on VMs on openstack (created by nova).

**Comment by poblin-orange** [comment]
Hello,
i think im hitting this issue too.
My contexte: flocker 1.11.0 / openstack juno/kvm (Cloudwatt iaas), ubuntu 14.04

The flocker cinder volume is correctly attached to the vm
```
dbce@inception:~/deployments$ cinder list |grep flocker
| b26d7552-a9b3-4b3e-8fad-85c9f09c683e |   in-use  | flocker-20cb67a5-09b8-4dc4-a718-9ed67241bf50 |  75  |   standard  |  false   | 4b77f557-df20-47ba-89bc-6310bb2b5e9d |

```
Im getting this issue

```
{"exception": "flocker.node.agents.blockdevice.UnattachedVolume", "task_level": [2, 2, 5], "action_type": "flocker:agent:discovery", "reason": "b26d7552-a9b3-4b3e-8fad-85c9f09c683e", "timestamp": 1461189753.873537, "task_uuid": "7c512b8a-3e99-44e3-bb78-484ab521d1fd", "action_status": "failed"}
{"exception": "flocker.node.agents.blockdevice.UnattachedVolume", "reason": "b26d7552-a9b3-4b3e-8fad-85c9f09c683e", "timestamp": 1461189753.873933, "traceback": "Traceback: <class 'flocker.node.agents.blockdevice.UnattachedVolume'>: b26d7552-a9b3-4b3e-8fad-85c9f09c683e\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py:102:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:534:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:592:output\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py:529:output_CONVERGE\n--- <exception caught here> ---\n/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1798:discover_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1345:_count_calls\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1764:_discover_raw_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:2032:get_device_path\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py:686:get_device_path\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py:638:_get_device_path_virtio_blk\n", "message_type": "eliot:traceback", "task_uuid": "7c512b8a-3e99-44e3-bb78-484ab521d1fd", "task_level": [2, 3]}



```

However, it seems the cinder provided device path is not correct (the vm has a non flocker volume, detected by ubuntu as /dev/vdb, the flocker volume is seen by ubuntu as /dev/vdc). Cinder api indicates flocker volume as /dev/vdb (see below)

```
|                Property               |                                                                                                    Value                                                                                                     |                                                                                                                                                                                                        
+---------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                                                                                                                                                                                                        
|              attachments              | [{u'device': u'/dev/vdb', u'server_id': u'5bca4ff9-4133-495b-8d52-e2e6cbe3b452', u'id': u'0d16374d-e98e-499a-88e2-5e6f6aebe1f4', u'host_name': None, u'volume_id': u'0d16374d-e98e-499a-88e2-5e6f6aebe1f4'}] |                                                                                                                                                                                                        
|           availability_zone           |                                                                                                     prd1                                                                                                     |
|                bootable               |                                                                                                    false                                                                                                     |
|               created_at              |                                                                                          2016-04-20T21:23:37.000000                                                                                          |
|          display_description          |                                                                                                     None                                                                                                     |
|              display_name             |                                                                                 flocker-ed6b31b8-28ab-44a7-b5ce-ad28e186ae2e                                                                                 |
|               encrypted               |                                                                                                    False                                                                                                     |
|                   id                  |                                                                                     0d16374d-e98e-499a-88e2-5e6f6aebe1f4                                                                                     |
|                metadata               |               {u'flocker-cluster-id': u'8fc9fa36-f88e-4b17-a2a9-c7f0e117725b', u'readonly': u'False', u'flocker-dataset-id': u'ed6b31b8-28ab-44a7-b5ce-ad28e186ae2e', u'attached_mode': u'rw'}               |
|      os-vol-tenant-attr:tenant_id     |                                                                                       a05bd5ca0b604cdb923680c219939986                                                                                       |
|   os-volume-replication:driver_data   |                                                                                                     None                                                                                                     |
| os-volume-replication:extended_status |                                                                                                     None                                                                                                     |
|                  size                 |                                                                                                      75                                                                                                      |
|              snapshot_id              |                                                                                                     None                                                                                                     |
|              source_volid             |                                                                                                     None                                                                                                     |
|                 status                |                                                                                                    in-use                                                                                                    |
|              volume_type              |                                                                                                   standard                                                                                                   |
+---------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


```

So i think openstack mistmatches device path.
It seem to be a know issue: 
https://bugs.launchpad.net/nova/+bug/1217874
http://lists.openstack.org/pipermail/openstack-dev/2013-April/007208.html

Does flocker directly use the device path provided by cinder ?

**Comment by poblin-orange** [comment]
as an additional hint, there seem to be a way to identify the correct device path from openstack metadata.
see https://www.chriscowley.me.uk/blog/2015/05/05/identify-and-mounting-cinder-volumes-in-openstack-heat/ (although a correct solution should not require cloud-init in the node vm)

**Comment by wallnerryan** [comment]
Thanks @poblin-orange will look into this. CC @wallrj

**Comment by wallrj** [comment]
@CBR09 wrote:
> Thanks @wallnerryan, Do you have any update on it?, or any suggestion for me to make flocker + cinder + flocker-docker-plugin work?.

Hey. Sorry for the delay in resolving this issue. And thanks for providing the diagnostic information.

It seems to me that in your case, the Nova API is correctly reporting the attached device path (`/dev/vdb`) but your openstack / virtio is not populating the device serial number, which we rely on to match the device inside the OS to the Cinder volume.

@poblin-orange Thanks for the information and links. We are already using the block device serial number (as described in that blog post).

The process is roughly:
 * Look up the device path reported by the Nova API
 * If the reported path matches the pattern `/dev/vd?` (this is our crude method of detecting that the platform is using `virtio_blk` driver...and perhaps this is broken)
 * Look for a symlink in `/dev/disk/by-id/virtio-<cinder volume id>` and return the target of that link....which will usually be `/dev/vdb` but sometimes `/dev/vd?` if something else has already occupied the `vdb`

(https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/cinder.py#L695)

And it seems that both of you are hitting this code path.

In @CBR09 's case, it looks like Nova is reporting the correct device path, `dev/vdb`, but Flocker is ignoring it because the disk doesn't have the expected serial number.
Additionally your syslog contains the following snippet:
```
Apr 12 10:11:32 ubuntu1 kernel: [65849.676691] virtio-pci 0000:00:06.0: enabling device (0000 -> 0003)
Apr 12 10:11:32 ubuntu1 kernel: [65849.709390] ACPI: PCI Interrupt Link [LNKB] enabled at IRQ 11
Apr 12 10:11:32 ubuntu1 kernel: [65849.712513] virtio-pci 0000:00:06.0: irq 45 for MSI/MSI-X
Apr 12 10:11:32 ubuntu1 kernel: [65849.712538] virtio-pci 0000:00:06.0: irq 46 for MSI/MSI-X
Apr 12 10:11:32 ubuntu1 kernel: [65849.712736] blk-mq: CPU -> queue map
Apr 12 10:11:32 ubuntu1 kernel: [65849.712738]   CPU 0 -> Queue 0
Apr 12 10:11:32 ubuntu1 kernel: [65849.717240]  vdb: unknown partition table

```

Interesting to read about `blk-mq` ... an optimization for providing fast access to  SSD drives...from virtual machines?


@poblin-orange: in your case, it sounds like `/dev/vdb` is reported by Nova, but that device name is already occupied by a non-cinder device in the OS and again the serial number based identification isn't working. 

Some thoughts:
 * You are using an OpenStack configuration which we have not tested (quite likely) which uses `/dev/vd?` for attached Cinder volumes but which does not populate the disk serial numbers of those volumes.
 * The serial number is present but does not match the pattern `virtio-<cinder volume id>`
 * The serial number is present but the OS is not creating a symlink in `/dev/disk/by-id/`


If your OpenStack system is anything like our devstack testing environment you'll be able to see the cinder volume IDs in the process  listing on the OpenStack host machine.

```
[stack@devstack-onmetal-1 ~]$ cinder list
+--------------------------------------+-----------+----------------------------------------------+------+-------------+----------+--------------------------------------+
|                  ID                  |   Status  |                     Name                     | Size | Volume Type | Bootable |             Attached to              |
+--------------------------------------+-----------+----------------------------------------------+------+-------------+----------+--------------------------------------+
| 1b55aa46-5cc3-4a10-9352-9179c8d4bf85 |   in-use  |                                              |  10  | lvmdriver-1 |   true   | 33d406cf-e8ef-40a8-b253-6844a4642cb5 |
| 60224920-781a-417b-84f1-bab40135aa8b |   in-use  |                                              |  10  | lvmdriver-1 |   true   | a9faf569-a455-411b-a0f1-009ed47ae27b |
| a556780a-083a-4c0b-9a36-04ec48c55b90 |   in-use  |                                              |  10  | lvmdriver-1 |   true   | 2fa67f2e-58b6-4023-862f-579e679b5bb4 |
| a7438ca7-b563-4be7-8ff8-c0c079ecd415 |   in-use  |                                              |  10  | lvmdriver-1 |   true   | 5db59fdb-a925-4942-8bf9-6d0c4699e13b |
| c708fa7f-e37e-4733-b4d6-57dd1eaba897 | available |             vm1-centos7bootable              |  25  | lvmdriver-1 |   true   |                                      |
| e08a390a-ba60-43e5-900e-d124257a8ab3 |   in-use  | flocker-514ecf20-931d-49d2-801c-c67c12a5ca40 |  1   | lvmdriver-1 |  false   | a9faf569-a455-411b-a0f1-009ed47ae27b |
+--------------------------------------+-----------+----------------------------------------------+------+-------------+----------+--------------------------------------+
```


```
[stack@devstack-onmetal-1 ~]$ ps faux | grep 1b55aa46-5cc3-4a10-9352-9179c8d4bf85
stack    22194  0.0  0.0   9036   672 pts/19   S+   19:17   0:00              \_ grep --color=auto 1b55aa46-5cc3-4a10-9352-9179c8d4bf85
qemu      2822  2.9  1.9 1024672 653664 ?      Sl   Mar18 1643:34 /usr/libexec/qemu-kvm -name instance-00000012 -S -machine pc-i440fx-rhel7.0.0,accel=kvm,usb=off -m 512 -realtime mlock=off -smp 1,sockets=1,cores=1,threads=1 -uuid 33d406cf-e8ef-40a8-b253-6844a4642cb5 -smbios type=1,manufacturer=OpenStack Foundation,product=OpenStack Nova,version=13.0.0,serial=e93ceb52-4975-484b-a6ff-4895a762773e,uuid=33d406cf-e8ef-40a8-b253-6844a4642cb5,family=Virtual Machine -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-instance-00000012/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -no-hpet -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/opt/stack/data/nova/instances/33d406cf-e8ef-40a8-b253-6844a4642cb5/disk.config,if=none,id=drive-ide0-1-1,readonly=on,format=raw,cache=none -device ide-cd,bus=ide.1,unit=1,drive=drive-ide0-1-1,id=ide0-1-1 -drive file=/dev/disk/by-path/ip-104.130.20.211:3260-iscsi-iqn.2010-10.org.openstack:volume-1b55aa46-5cc3-4a10-9352-9179c8d4bf85-lun-1,if=none,id=drive-virtio-disk0,format=raw,serial=1b55aa46-5cc3-4a10-9352-9179c8d4bf85,cache=none,aio=native -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x4,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -netdev tap,fd=23,id=hostnet0,vhost=on,vhostfd=26 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=fa:16:3e:53:19:b0,bus=pci.0,addr=0x3 -chardev file,id=charserial0,path=/opt/stack/data/nova/instances/33d406cf-e8ef-40a8-b253-6844a4642cb5/console.log -device isa-serial,chardev=charserial0,id=serial0 -chardev pty,id=charserial1 -device isa-serial,chardev=charserial1,id=serial1 -vnc 127.0.0.1:2 -k en-us -vga cirrus -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5 -msg timestamp=on

```

If you still have the clusters set up, can you provide the output of these commands in the gues OS:

```
# A listing of all the files and symlinks in `/dev/disk`
ls -l /dev/disk/by-id/

# flocker-diagnostics run as root (it will only include the complete disk information if run as root)
sudo flocker-diagnostics
```

And on the OpenStack host:
```
# A complete list of libvirt instances and the devices attached
virsh -c qemu:///system list

# A dump of the configuration of the Flocker host that has the undetected volume attached eg
virsh -c qemu:///system dumpxml instance-00000011
```

Can you also both please check whether your openstack includes this patch:
 https://github.com/openstack/nova/commit/3a47c02c58cefed0e230190b4bcef14527c82709

(this is where nova grew the ability to set the serial number on libvirt disks)

Hopefully this will help me figure out how your openstack machines are configured and whether they are configuring the virtual disk devices with serial numbers.

**Comment by poblin-orange** [comment]
hello @wallrj 
thanks for your feed back.
Unfortunatly, i dont have acces to iaas level logs.

But here is what i get in my vm

```
root@4b5aa10f-cb46-4bc6-b254-e932e10544d5:/dev/disk/by-id# ls -lrt
total 0
lrwxrwxrwx 1 root root  9 Apr 29 13:56 virtio-6ea73b81-555e-4a74-9 -> ../../vdb
lrwxrwxrwx 1 root root 10 Apr 29 13:56 virtio-6ea73b81-555e-4a74-9-part1 -> ../../vdb1
lrwxrwxrwx 1 root root  9 Apr 29 13:56 ata-QEMU_DVD-ROM_QM00004 -> ../../sr0
lrwxrwxrwx 1 root root  9 Apr 29 13:56 virtio-22b7400e-df70-4c22-b -> ../../vdc
```

The id are present, though truncated ?!
Im trying to confirm with my iaas provider that the device paths are wrong ...
Its Openstack Juno + so i guess the patch you indicate is present


below the volumes and vms details

```
root@4b5aa10f-cb46-4bc6-b254-e932e10544d5:/dev/disk/by-id# mount
/dev/vda1 on / type ext4 (rw)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
/dev/vda3 on /var/vcap/data type ext4 (rw)
tmpfs on /var/vcap/data/sys/run type tmpfs (rw,size=1m)
/var/vcap/data/root_tmp on /tmp type ext4 (rw,noexec)
/dev/vdb1 on /var/vcap/store type ext4 (rw)

/dev/vdb1       10190092 1286236   8363188  14% /var/vcap/store

=> /dev/vdb fait 10Go, ce qui correspond au volume volume-159c64aa-b593-4bae-865b-1532d8557587 

le volume  flocker-0e7a77aa-99d4-4240-850e-cd5e4913702f est attaché au niveau openstack, mais pas monté dans linux. cloudwatt le positionne à tort sur /dev/vdb qui est deja pris


+--------------------------------------+--------------------------------------------------------------------------------------------------------+
| Property                             | Value                                                                                                  |
+--------------------------------------+--------------------------------------------------------------------------------------------------------+
| OS-DCF:diskConfig                    | AUTO                                                                                                   |
| OS-EXT-AZ:availability_zone          | nova                                                                                                   |
| OS-EXT-STS:power_state               | 1                                                                                                      |
| OS-EXT-STS:task_state                | -                                                                                                      |
| OS-EXT-STS:vm_state                  | active                                                                                                 |
| OS-SRV-USG:launched_at               | 2016-04-29T13:34:37.000000                                                                             |
| OS-SRV-USG:terminated_at             | -                                                                                                      |
| accessIPv4                           |                                                                                                        |
| accessIPv6                           |                                                                                                        |
| config_drive                         | True                                                                                                   |
| created                              | 2016-04-29T13:31:21Z                                                                                   |
| flavor                               | n2.cw.standard-1 (42)                                                                                  |
| hostId                               | caa026052cdc8a6497e96f65f1ef3c7ea7a6cef69e9aa47a7b15b6ee                                               |
| id                                   | 847b94c0-c3f7-4be8-a28a-52fc4ffba0a4                                                                   |
| image                                | BOSH-e539f6f4-2268-4e25-9c5d-11c0825c209a (e9dd8e7d-2974-406c-b17e-10c21aec9b71)                       |
| key_name                             | bosh                                                                                                   |
| metadata                             | {"director": "bosh-master-cloudwatt-qa", "index": "0", "job": "flocker-node", "deployment": "flocker"} |
| name                                 | vm-dc78eb25-2615-4fa9-8cbe-499ba05cd9cc                                                                |
| os-extended-volumes:volumes_attached | [{"id": "6ea73b81-555e-4a74-97db-4541eec326dd"}, {"id": "22b7400e-df70-4c22-b905-f4c898c19c52"}]       |
| private network                      | 10.100.0.16                                                                                            |
| progress                             | 0                                                                                                      |
| security_groups                      | default                                                                                                |
| status                               | ACTIVE                                                                                                 |
| tenant_id                            | a05bd5ca0b604cdb923680c219939986                                                                       |
| updated                              | 2016-04-29T13:34:38Z                                                                                   |
| user_id                              | 0e58049c7cf34a3cac06ccf0f9e0ce68                                                                       |
+--------------------------------------+--------------------------------------------------------------------------------------------------------+





-------------------------------------------------------+                                                                                                                                        
|                Property               |                                                                                                    Value                                                                                                     |                                                                                                                                        
+---------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                                                                                                                                        
|              attachments              | [{u'device': u'/dev/vdb', u'server_id': u'847b94c0-c3f7-4be8-a28a-52fc4ffba0a4', u'id': u'22b7400e-df70-4c22-b905-f4c898c19c52', u'host_name': None, u'volume_id': u'22b7400e-df70-4c22-b905-f4c898c19c52'}] |                                                                                                                                        
|           availability_zone           |                                                                                                     prd1                                                                                                     |
|                bootable               |                                                                                                    false                                                                                                     |
|               created_at              |                                                                                          2016-04-29T13:42:36.000000                                                                                          |
|          display_description          |                                                                                                     None                                                                                                     |
|              display_name             |                                                                                 flocker-0e7a77aa-99d4-4240-850e-cd5e4913702f                                                                                 |
|               encrypted               |                                                                                                    False                                                                                                     |
|                   id                  |                                                                                     22b7400e-df70-4c22-b905-f4c898c19c52                                                                                     |
|                metadata               |               {u'flocker-cluster-id': u'8fc9fa36-f88e-4b17-a2a9-c7f0e117725b', u'readonly': u'False', u'flocker-dataset-id': u'0e7a77aa-99d4-4240-850e-cd5e4913702f', u'attached_mode': u'rw'}               |
|      os-vol-tenant-attr:tenant_id     |                                                                                       a05bd5ca0b604cdb923680c219939986                                                                                       |
|   os-volume-replication:driver_data   |                                                                                                     None                                                                                                     |
| os-volume-replication:extended_status |                                                                                                     None                                                                                                     |
|                  size                 |                                                                                                      75                                                                                                      |
|              snapshot_id              |                                                                                                     None                                                                                                     |
|              source_volid             |                                                                                                     None                                                                                                     |
|                 status                |                                                                                                    in-use                                                                                                    |
|              volume_type              |                                                                                                   standard                                                                                                   |
+---------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


-------------------------------------------------------+                                                                                                                                        
|                Property               |                                                                                                    Value                                                                                                     |                                                                                                                                        
+---------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                                                                                                                                        
|              attachments              | [{u'device': u'/dev/vdc', u'server_id': u'847b94c0-c3f7-4be8-a28a-52fc4ffba0a4', u'id': u'6ea73b81-555e-4a74-97db-4541eec326dd', u'host_name': None, u'volume_id': u'6ea73b81-555e-4a74-97db-4541eec326dd'}] |                                                                                                                                        
|           availability_zone           |                                                                                                     prd1                                                                                                     |
|                bootable               |                                                                                                    false                                                                                                     |
|               created_at              |                                                                                          2016-04-29T13:39:40.000000                                                                                          |
|          display_description          |                                                                                                                                                                                                              |
|              display_name             |                                                                                 volume-159c64aa-b593-4bae-865b-1532d8557587                                                                                  |
|               encrypted               |                                                                                                    False                                                                                                     |
|                   id                  |                                                                                     6ea73b81-555e-4a74-97db-4541eec326dd                                                                                     |
|                metadata               |                                                                               {u'readonly': u'False', u'attached_mode': u'rw'}                                                                               |
|      os-vol-tenant-attr:tenant_id     |                                                                                       a05bd5ca0b604cdb923680c219939986                                                                                       |
|   os-volume-replication:driver_data   |                                                                                                     None                                                                                                     |
| os-volume-replication:extended_status |                                                                                                     None                                                                                                     |
|                  size                 |                                                                                                      10                                                                                                      |
|              snapshot_id              |                                                                                                     None                                                                                                     |
|              source_volid             |                                                                                                     None                                                                                                     |
|                 status                |                                                                                                    in-use                                                                                                    |
|              volume_type              |                                                                                                   standard                                                                                                   |
+---------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

**Comment by wallrj** [comment]
Thanks @poblin-orange 

The only unusual things I see in your Cinder output is that the device reported by Cinder API and the device linked to in the OS are switched. So

```
virtio-6ea73b81-555e-4a74-9 -> ../../vdb

AND

[{u'device': u'/dev/vdc', u'server_id': u'847b94c0-c3f7-4be8-a28a-52fc4ffba0a4', u'id': u'6ea73b81-555e-4a74-97db-4541eec326dd', u'host_name': None, u'volume_id': u'6ea73b81-555e-4a74-97db-4541eec326dd'}] |          ```                                                                                                                              

vs

```
virtio-22b7400e-df70-4c22-b -> ../../vdc

AND

[{u'device': u'/dev/vdb', u'server_id': u'847b94c0-c3f7-4be8-a28a-52fc4ffba0a4', u'id': u'22b7400e-df70-4c22-b905-f4c898c19c52', u'host_name': None, u'volume_id': u'22b7400e-df70-4c22-b905-f4c898c19c52'}]
```

It'd be interesting to see your Flocker logs, syslog and dmesg output.
You can archive all that information using flocker-diagnostics, but it's important to run it as root on the node, in order to get the complete logs.

```
# Export syslog and flocker logs
sudo flocker-diagnostics
``` 

Upload the logs somewhere and ping me directly rather than share them here.

**Comment by poblin-orange** [comment]
@wallrj 
yes i agree there is a device switch issue. I raised an issue on my openstack provider.

The deployment mode i use is docker based. I tried to docker exec the flocker-diagnostics command but no luck so far.

```
root@4b5aa10f-cb46-4bc6-b254-e932e10544d5:~# export DOCKER_COMMAND="/var/vcap/packages/docker/bin/docker -H unix:///var/vcap/sys/run/docker/docker.sock"
root@4b5aa10f-cb46-4bc6-b254-e932e10544d5:~# $DOCKER_COMMAND ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS               NAMES
9fed7b4e0bab        clusterhq/flocker-dockerplugin:1.11.0    "/usr/sbin/flocker-do"   2 hours ago         Up 2 hours                              flocker_docker_plugin
b8faf690a5af        clusterhq/flocker-dataset-agent:1.11.0   "/tmp/wrap_dataset_ag"   2 hours ago         Up 2 hours                              flocker_dataset_agent

```

```
root@4b5aa10f-cb46-4bc6-b254-e932e10544d5:~# $DOCKER_COMMAND exec -it  b8faf690a5af  /bin/bash

root@4b5aa10f-cb46-4bc6-b254-e932e10544d5:/# sudo /opt/flocker/bin/python /opt/flocker/bin/flocker-diagnostics                                     
Unhandled Error                                                                                                                                    
Traceback (most recent call last):                                                                                                                 
  File "/opt/flocker/local/lib/python2.7/site-packages/flocker/node/script.py", line 662, in flocker_diagnostics_main                              
    logging=False,                                                                                                                                 
  File "/opt/flocker/local/lib/python2.7/site-packages/flocker/common/script.py", line 295, in main                                                
    self._react(run_and_log, [], _reactor=self._reactor)                                                                                           
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/task.py", line 882, in react                                               
    finished = main(_reactor, *argv)                                                                                                               
  File "/opt/flocker/local/lib/python2.7/site-packages/flocker/common/script.py", line 283, in run_and_log                                         
    d = maybeDeferred(self.script.main, reactor, options)                                                                                          


```

By the way, i had the opportunity to test the same deployment on another openstack iaas provider (Juno, Mirantis based) and the result is better.
The volumes gets created, attached, corretly map in /dev/disk/by-id.
Only issue i had is the /dev/disk-by-id path is not updated UNTIL i reboot the node vm (which defeats the purpose). I can raise a different issue if you think its more convenient than this issue
thanks

**Comment by wallnerryan** [comment]
@poblin-orange you would need to export the logs from `docker logs` if you are using docker based. Flocker diagnostics doesnt support the containerized version.
