### ISSUE TITLE
Can't start  flocker-dataset-agent.service or flocker-container-agent.service

### ISSUE THREAD

**Issue by scotty-c** [ClusterHQ/flocker#2766]
Good afternoon,

I am getting the following error with the flocker-container-agent.service

````
Apr 18 03:53:42 flocker-02 systemd[1]: Started Flocker Dataset Agent.
Apr 18 03:53:42 flocker-02 systemd[1]: Starting Flocker Dataset Agent...
Apr 18 03:53:43 flocker-02 flocker-dataset-agent[8945]: {"task_uuid": "3a16a839-1b5b-4d50-893a-5884ad7ca507", "error": false, "timestamp": 1460951623.950877, "message": "Log opened.", "message_type": "twisted:log", "task_level": [1]}
Apr 18 03:53:43 flocker-02 flocker-dataset-agent[8945]: {"task_uuid": "0f7599cc-6c75-4bd6-967b-2cd3c577ee11", "task_level": [1], "action_type": "flocker:node:script:get_external_ip", "timestamp": 1460951623.95468, "host": "flocker-01.local.test", "action_status": "started", "port": 4524}
Apr 18 03:53:43 flocker-02 flocker-dataset-agent[8945]: {"task_uuid": "0f7599cc-6c75-4bd6-967b-2cd3c577ee11", "task_level": [2], "action_type": "flocker:node:script:get_external_ip", "local_ip": "172.17.8.102", "timestamp": 1460951623.956358, "action_status": "succeeded"}
Apr 18 03:53:43 flocker-02 flocker-dataset-agent[8945]: {"task_uuid": "dd3e523e-6da8-41d2-a9fb-cb1654f8d33f", "error": true, "timestamp": 1460951623.957557, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 81, in flocker_dataset_agent_main\n    options=options,\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 295, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 283, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 292, in main\n    self.service_factory(reactor, options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 597, in get_service\n    deployer = agent_service.get_deployer(api)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 553, in get_deployer\n    node_uuid = self.node_credential.uuid\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 533, in uuid\n    return UUID(hex=common_name[len(self._UUID_PREFIX):])\n  File \"/usr/lib64/python2.7/uuid.py\", line 134, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nexceptions.ValueError: badly formed hexadecimal UUID string\n", "message_type": "twisted:log", "task_level": [1]}
Apr 18 03:53:43 flocker-02 flocker-dataset-agent[8945]: {"task_uuid": "b548b9be-0cd5-4bab-a43b-4eff7ffb49fc", "error": true, "timestamp": 1460951623.957934, "message": "main function encountered error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 81, in flocker_dataset_agent_main\n    options=options,\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 295, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 283, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 292, in main\n    self.service_factory(reactor, options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 597, in get_service\n    deployer = agent_service.get_deployer(api)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 553, in get_deployer\n    node_uuid = self.node_credential.uuid\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 533, in uuid\n    return UUID(hex=common_name[len(self._UUID_PREFIX):])\n  File \"/usr/lib64/python2.7/uuid.py\", line 134, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nexceptions.ValueError: badly formed hexadecimal UUID string\n", "message_type": "twisted:log", "task_level": [1]}
Apr 18 03:53:43 flocker-02 flocker-dataset-agent[8945]: {"task_uuid": "185c9c2c-4d44-45b3-8547-54ee01f86641", "error": false, "timestamp": 1460951623.958113, "message": "Main loop terminated.", "message_type": "twisted:log", "task_level": [1]}
Apr 18 03:53:44 flocker-02 systemd[1]: flocker-dataset-agent.service: main process exited, code=exited, status=1/FAILURE
Apr 18 03:53:44 flocker-02 systemd[1]: Unit flocker-dataset-agent.service entered failed state.
Apr 18 03:53:44 flocker-02 systemd[1]: flocker-dataset-agent.service failed.
Apr 18 03:53:44 flocker-02 systemd[1]: flocker-dataset-agent.service holdoff time over, scheduling restart.
Apr 18 03:53:44 flocker-02 systemd[1]: start request repeated too quickly for flocker-dataset-agent.service
Apr 18 03:53:44 flocker-02 systemd[1]: Failed to start Flocker Dataset Agent.
Apr 18 03:53:44 flocker-02 systemd[1]: Unit flocker-dataset-agent.service entered failed state.
Apr 18 03:53:44 flocker-02 systemd[1]: flocker-dataset-agent.service failed.

````

and with the  flocker-dataset-agent.service
````
Apr 18 04:00:50 flocker-02 systemd[1]: Started Flocker Container Agent.
Apr 18 04:00:50 flocker-02 systemd[1]: Starting Flocker Container Agent...
Apr 18 04:00:50 flocker-02 flocker-container-agent[9145]: {"task_uuid": "22d27f0a-74bc-48f5-993a-7d1d71bcb387", "error": false, "timestamp": 1460952050.765611, "message": "Log opened.", "message_type": "twisted:log", "task_level": [1]}
Apr 18 04:00:50 flocker-02 flocker-container-agent[9145]: {"task_uuid": "a91bd0a8-6bbf-4d02-a5b2-445cb7074057", "task_level": [1], "action_type": "flocker:node:script:get_external_ip", "timestamp": 1460952050.76827, "host": "flocker-01.local.test", "action_status": "started", "port": 4524}
Apr 18 04:00:50 flocker-02 flocker-container-agent[9145]: {"task_uuid": "a91bd0a8-6bbf-4d02-a5b2-445cb7074057", "task_level": [2], "action_type": "flocker:node:script:get_external_ip", "local_ip": "172.17.8.102", "timestamp": 1460952050.770161, "action_status": "succeeded"}
Apr 18 04:00:50 flocker-02 flocker-container-agent[9145]: {"task_uuid": "bf95b04f-48df-4a6a-9fae-65ddd008005d", "error": true, "timestamp": 1460952050.775076, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 106, in flocker_container_agent_main\n    options=ContainerAgentOptions()\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 295, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 283, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 292, in main\n    self.service_factory(reactor, options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 343, in get_service\n    node_uuid=tls_info.node_credential.uuid, hostname=ip,\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 533, in uuid\n    return UUID(hex=common_name[len(self._UUID_PREFIX):])\n  File \"/usr/lib64/python2.7/uuid.py\", line 134, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nexceptions.ValueError: badly formed hexadecimal UUID string\n", "message_type": "twisted:log", "task_level": [1]}
Apr 18 04:00:50 flocker-02 flocker-container-agent[9145]: {"task_uuid": "ac0947ed-961b-4007-a38d-4d7940788118", "error": true, "timestamp": 1460952050.77549, "message": "main function encountered error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 106, in flocker_container_agent_main\n    options=ContainerAgentOptions()\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 295, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 283, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 292, in main\n    self.service_factory(reactor, options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 343, in get_service\n    node_uuid=tls_info.node_credential.uuid, hostname=ip,\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 533, in uuid\n    return UUID(hex=common_name[len(self._UUID_PREFIX):])\n  File \"/usr/lib64/python2.7/uuid.py\", line 134, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nexceptions.ValueError: badly formed hexadecimal UUID string\n", "message_type": "twisted:log", "task_level": [1]}
Apr 18 04:00:50 flocker-02 flocker-container-agent[9145]: {"task_uuid": "f2ed24b8-daf9-4b36-9e88-7a8f63a44346", "error": false, "timestamp": 1460952050.775751, "message": "Main loop terminated.", "message_type": "twisted:log", "task_level": [1]}
Apr 18 04:00:50 flocker-02 systemd[1]: flocker-container-agent.service: main process exited, code=exited, status=1/FAILURE
Apr 18 04:00:50 flocker-02 systemd[1]: Unit flocker-container-agent.service entered failed state.
Apr 18 04:00:50 flocker-02 systemd[1]: flocker-container-agent.service failed.
Apr 18 04:00:51 flocker-02 systemd[1]: flocker-container-agent.service holdoff time over, scheduling restart.
Apr 18 04:00:51 flocker-02 systemd[1]: start request repeated too quickly for flocker-container-agent.service
Apr 18 04:00:51 flocker-02 systemd[1]: Failed to start Flocker Container Agent.
Apr 18 04:00:51 flocker-02 systemd[1]: Unit flocker-container-agent.service entered failed state.
Apr 18 04:00:51 flocker-02 systemd[1]: flocker-container-agent.service failed.
````

I am using Centos 7 with Flocker 1.11.0

**Comment by wallnerryan** [comment]
@scotty-c What backend are you trying to use?

**Comment by scotty-c** [comment]
@wallnerryan Sorry for leaving out that information. At the moment I am just using the loopback backend for testing

**Comment by wallnerryan** [comment]
Can you run `flocker-diagnostics` and send us the TAR file?

**Comment by wallrj** [comment]
The formatted error looks like

```
main function encountered error
Traceback (most recent call last):
  File "/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py", line 81, in flocker_dataset_agent_main
    options=options,
  File "/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py", line 295, in main
    self._react(run_and_log, [], _reactor=self._reactor)
  File "/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py", line 882, in react
    finished = main(_reactor, *argv)
  File "/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py", line 283, in run_and_log
    d = maybeDeferred(self.script.main, reactor, options)
--- <exception caught here> ---
  File "/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py", line 292, in main
    self.service_factory(reactor, options)
  File "/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py", line 597, in get_service
    deployer = agent_service.get_deployer(api)
  File "/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py", line 553, in get_deployer
    node_uuid = self.node_credential.uuid
  File "/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py", line 533, in uuid
    return UUID(hex=common_name[len(self._UUID_PREFIX):])
  File "/usr/lib64/python2.7/uuid.py", line 134, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
exceptions.ValueError: badly formed hexadecimal UUID string

```


```

{
  "task_uuid": "b548b9be-0cd5-4bab-a43b-4eff7ffb49fc",
  "error": true,
  "timestamp": 1460951623.957934,
  "message": "main function encountered error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 81, in flocker_dataset_agent_main\n    options=options,\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 295, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 283, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 292, in main\n    self.service_factory(reactor, options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 597, in get_service\n    deployer = agent_service.get_deployer(api)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 553, in get_deployer\n    node_uuid = self.node_credential.uuid\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 533, in uuid\n    return UUID(hex=common_name[len(self._UUID_PREFIX):])\n  File \"/usr/lib64/python2.7/uuid.py\", line 134, in __init__\n    raise ValueError('badly formed hexadecimal UUID string')\nexceptions.ValueError: badly formed hexadecimal UUID string\n",
  "message_type": "twisted:log",
  "task_level": [
    1
  ]
}
```

Which comes from the following function / property

```
    @property
    def uuid(self):
        common_name = self.credential.certificate.getSubject().CN
        return UUID(hex=common_name[len(self._UUID_PREFIX):])

```
Some thoughts:
 * I wonder if your certificate is somehow non-standard. 
* Did you generate the certificates using `flocker-ca` or using `openssl` ?
* Did you accidentally copy the wrong certificate to the node?


A properly constructed node certificate should look something like this:

```
(master) [/tmp/flocker]$ openssl x509  -text -in 28f2f1cd-02e4-42ec-9d11-c206945098c3.crt
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            91:f5:60:c3:9a:63:b3:80:1f:1c:22:1f:cf:5c:92:ce
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: OU=25be7b2a-5dee-4055-942a-ac5513c91b29, CN=test-cluster-1
        Validity
            Not Before: Apr 25 17:20:06 2016 GMT
            Not After : Apr 20 17:20:06 2036 GMT
        Subject: OU=25be7b2a-5dee-4055-942a-ac5513c91b29, CN=node-28f2f1cd-02e4-42ec-9d11-c206945098c3


```

Note that the `Subject > CN (Common Name)` of the node certificate should begin with `node-` followed by the node's UUID.

Run `openssl x509  -text -in /etc/flocker/node.crt` on the faulty node and take a look at the output. Paste it here if you are willing to share.

**Comment by scotty-c** [comment]
Thanks @wallnerryan and @wallrj , I am writing a Puppet module to deploy flocker at scale. There was an issue with the way I was auto generating the certificates and passing them to the nodes.  @wallrj Your information was very valuable to find the issue. It's now resolved

**Comment by wallrj** [comment]
Thanks @scotty-c glad you're up and running. We'll be happy to support you if you run into any more problems. We've benchmarked Flocker 1.11 with ~50 nodes and ~800 stateful containers on GCE so it'd be interesting to know the size of your cluster.

**Comment by wallnerryan** [comment]
Great!, Also, @scotty-c we also have [an ansible role](https://github.com/ClusterHQ/ansible-role-flocker) to deploy flocker, I'de be interested to hear your requirements/reasons for puppet.

Thanks
R

**Comment by scotty-c** [comment]
@wallnerryan What is your email ? We can carry on the conversation there

**Comment by wallnerryan** [comment]
Thanks @scotty-c ryan.wallner@clusterhq.com

**Comment by wallnerryan** [comment]
closing

**Comment by eddy-ru** [comment]
@wallrj i do as u say but my service or not ，I have the same error and the questioner, please advise thks brother
