### ISSUE TITLE
No known node with address IP

### ISSUE THREAD

**Issue by akhildangore** [ClusterHQ/flocker#2821]
Hi Team,

I am new to flocker and getting above error: No known node with address IP, please let me know why i am getting this.

Note : IP is not public, I am using local network (node1 and node2), both are in same network.

**Comment by wallnerryan** [comment]
@akhildangore 

Can you please post the real error here from the logs?

Alternatively provide the tar output from `flocker-diagnostics` on the node with the error and send to support@clusterhq.com

**Comment by akhildangore** [comment]
I have completed following steps on ubuntu 14.04:

1. Installation the Flocker Client
   <https://docs.clusterhq.com/en/latest/docker-integration/install-client.html>
2. Installing the Flocker Node Services
   <https://docs.clusterhq.com/en/latest/docker-integration/install-node.html>
3. Configuring Cluster Authentication
   <https://docs.clusterhq.com/en/latest/docker-integration/configuring-authentication.html>
4. Enabling the Flocker Control Service
   <https://docs.clusterhq.com/en/latest/docker-integration/enabling-control-service.html>

And we are getting below error:

Form Client 
root@root-Flocker:/home/user0/Documents/Docker# flocker-deploy  172.17.222.42 deployment-1.yml docker-compose.yml

---> No known node with address 172.17.222.42.

Currently I have above info. I need to check how to see logs.
Can you provide me document link for debugging or logs guidance ?

**Comment by wallnerryan** [comment]
First off, I would recommend using [FlockerCTL](https://docs.clusterhq.com/en/latest/flocker-features/flockerctl.html) or the [Docker CLI with the Flocker Docker Plugin](https://docs.clusterhq.com/en/latest/docker-integration/enabling-agent-service.html#testing-the-flocker-plugin-for-docker) instead of `flocker-deploy` since it has been deprecated, meaning no more development will happen with it.  

Also, what does your deployment and application YAML files look like. The error seems to be from the control host not recognizing the node `172.17.222.42`  as a valid application node. Make sure you are only trying to deploy to nodes that run the `flocker-dataset-agent` and `flocker-control-agent` and that each one of these nodes have a unique `node.crt` and `node.key`.

Here is the link to how to debug and provide logs.
https://docs.clusterhq.com/en/latest/administering/debugging.html#debugging-flocker

**Comment by akhildangore** [comment]
Hi Wallnerryan,

Thanks for reply.....

I am very confused now,  Can you just help me with proper steps in sequence that will be great help ?  I will not expect in details....just titles.

And if  flocker-deploy is deprecated, what are steps and commands ?

**Comment by wallnerryan** [comment]
install Docker and Flocker Docker Plugin on your flocker cluster and you can use docker cli like this `docker volume create -d flocker --name myVolume -o size=10GB profile=gold`

**Comment by akhilcalsoft** [comment]
Hi wall nerryan,

Thanks for all help......

I have installed flockerctl but it is giving me error when run flockerctl list-nodes.
Unhandled Error
Traceback (most recent call last):
  File "/opt/flocker/bin/flockerctl", line 9, in <module>
    load_entry_point('UnofficialFlockerTools==0.6', 'console_scripts', 'flockerctl')()
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 381, in _main
    react(main, sys.argv[1:])
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/task.py", line 882, in react
    finished = main(_reactor, *argv)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 361, in main
    d = defer.maybeDeferred(base.subOptions.run)
--- <exception caught here> ---
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 96, in run
    self.client = get_client(self.parent)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 35, in get_client
    user = config["users"][0]
exceptions.TypeError: string indices must be integers, not str

main function encountered error
Traceback (most recent call last):
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/task.py", line 882, in react
    finished = main(_reactor, *argv)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 372, in main
    d.addErrback(err)
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 328, in addErrback
    errbackKeywords=kw)
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 371, in err
    reactor.stop()
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/base.py", line 581, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

**Comment by akhilcalsoft** [comment]
I have resolved this issue.......please ignore. environment variables is not set properly

**Comment by wallnerryan** [comment]
Thanks for the update @akhilcalsoft. Closing this issue now.
