### ISSUE TITLE
Ubuntu 16.04 and Docker 1.12 - Flocker-CLI and Flocker Docker Plugin both broken

### ISSUE THREAD

**Issue by garybottom** [ClusterHQ/flocker#2931]
Ubuntu 16.04
Docker version 1.12.2

**Flocker Client (clusterhq-flocker-cli)**
Instructions used:  
https://docs.clusterhq.com/en/latest/docker-integration/install-client.html#installing-on-ubuntu-16-04-64-bit
Apt Repo:
Get:10 https://clusterhq-archive.s3.amazonaws.com/ubuntu/16.04/amd64  Release [18 B]

apt-get install clusterhq-flocker-cli 
Installs without errors.

Error (with or without sudo):
$ flocker <any command here>
Traceback (most recent call last):
  File "/usr/bin/flocker", line 7, in <module>
    from flocker.cli.script import flocker_cli_main
ImportError: No module named script

**Flocker Docker Plugin**
Instructions used:
https://docs.clusterhq.com/en/latest/docker-integration/install-node.html#installing-on-ubuntu-16-04

Example (this error is produced by any use of -d flocker with docker volume):
sudo docker volume create -d flocker --name=testvol1 -o size=10G

Error response from daemon: create testvol1: create testvol1: Error looking up volume plugin flocker: legacy plugin: plugin not found

Neither of these are working via the installers or instructions.  Are there updated instructions and installers to work on Ubuntu 16.04 and Docker 1.12?

Cheers

**Comment by wallrj** [comment]
@garybottom Sorry for delayed reply.


> Error (with or without sudo):
> $ flocker
> Traceback (most recent call last):
> File "/usr/bin/flocker", line 7, in
> from flocker.cli.script import flocker_cli_main
> ImportError: No module named script

This is a known issue. Confusingly, the `flocker` command is not a documented or supported Flocker CLI right now.
It's a legacy of a previous version of Flocker.
The CLI for viewing and manipulating Flocker volumes can be installed according to these instructions:
 * https://docs.clusterhq.com/en/latest/flocker-features/flockerctl.html

> Error response from daemon: create testvol1: create testvol1: Error looking up volume plugin flocker: legacy plugin: plugin not found

This could be because the ``flocker-docker-plugin`` process isn't running.
Our acceptance tests install the plugin on Ubuntu 14.04 and on Ubuntu 16.04 with Docker 1.12 (latest) and run tests that call `docker volume create -d flocker`.
The tests are currently passing so I suspect that the problem might be caused by a misconfiguration or  something subtle on your particular system.

Take a look at the process list on that server and check that ``flocker-docker-plugin`` is running and that it is listening on a unix socket in the directory where Docker expects to find plugin sockets.

```
lsof -p $(pidof -x flocker-docker-plugin) | grep /run/docker/plugins
...
flocker-d 31292 root   12u     unix 0xffff88010b38a1c0      0t0 106271865 /run/docker/plugins/flocker/flocker.sock type=STREAM
```

Finally, check the logs from Flocker processes for exceptions and errors:
 * https://docs.clusterhq.com/en/latest/administering/debugging.html

Hope that helps.
