### ISSUE TITLE
Flocker tests are failing

### ISSUE THREAD

**Issue by Nayana-ibm** [ClusterHQ/flocker#2999]
Hi,

Ubuntu 16.04
Flocker 1.15.0

I have executed flocker test suite using "tox" command however getting below failures:

```
Failure: testtools.testresult.real._StringException: Empty attachments

Ran 2770 tests in 1030.296s
FAILED (skips=280, failures=5, successes=2485)
ERROR:   py27: commands failed
```

Tests failing with above error are: 
```
flocker.control.test.test_persistence.GenerationHashTests.test_consistent_hash
flocker.control.test.test_persistence.LatestGoldenFilesValid.test_can_create_latest_golden
flocker.restapi.testtools.ConfigurationContainersSchemaTests.test_fails_validation_maxItems_0
flocker.restapi.testtools.ConfigurationDatasetsCreateSchemaTests.test_fails_validation_pattern_1
flocker.restapi.testtools.ConfigurationDatasetsSchemaTests.test_fails_validation_pattern_1
```

Traceback for test
flocker.control.test.test_persistence.GenerationHashTests.test_consistent_hash: 

```
[FAIL]
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Empty attachments:
  twisted-eliot-log
  twisted-log

Traceback (most recent call last):
  File "/home/flocker/flocker/control/test/test_persistence.py", line 970, in test_consistent_hash
    Equals(TEST_DEPLOYMENT_1_HASH)
  File "/home/flocker/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = '\x87\x13\xcbG`\xd7\xab\x0f0\xd5\xd2x\xe8\x12]\x11'
actual    = '\xcf\x9e\xa0\xe7\x8f\x7f\xa3?\x8c\rH\xfb\x06\xc8\xeay'
```

I have followed below steps to build flocker:

```
git clone https://github.com/ClusterHQ/flocker
cd flocker
git checkout 1.15.0
sudo pip install -e .
sudo tox
```

Any idea on these failures? are these failures expected?

**Comment by adamtheturtle** [comment]
@Nayana-ibm ClusterHQ has shut down and therefore this repository is no longer being maintained. However, some ex-ClusterHQ developers are interested in maintaining Flocker - see http://scatterhq.com and get in touch!

Thanks
