### ISSUE TITLE
Upgrade to characteristic 14.1.0

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#688]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-688

If a user has installed a recent version of the `service_identity` package it will have installed `characteristic` v 14.1.0 as a dependency.

If that user then installs Flocker (outside of a virtualenv ...as in the case of Homebrew...I think) it may / will downgrade to Characteristic-0.1.0.

Then any Twisted code will start to break, because service_identity will be discovered, imported and attempt to use APIs that are only present in Characteristic-14.1.0.

We should update our dependencies to Characteristic-14.1.0 and create new Fedora packages for our Copr repo.

Here's an internal discussion on the matter:

```
engineering > service_identity

Richard Wall: David Gebler Like you said, I get a traceback if I've manually installed service_identity ...which relies on characteristic-14.1.0...then manually installed flocker which downgrades characteristic to 0.1.0

Richard Wall: Here's where we hid the warnings https://github.com/ClusterHQ/flocker/issues/317

Richard Wall: and here's the traceback

(562)(elk-tutorial-562 ✕ ▴2)[~/.../HybridLogic/flocker]$ trial flocker.node.test
flocker
  node
    test ...                                                            [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/trial/runner.py", line 586, in loadByNames
    things.append(self.findByName(name))
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/trial/runner.py", line 396, in findByName
    return reflect.namedAny(name)
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/python/reflect.py", line 242, in _importAndCheckStack
    return __import__(importName)
  File "/home/richard/projects/HybridLogic/flocker/flocker/node/__init__.py", line 12, in <module>
    from ._deploy import Deployer, NodeState, SSH_PRIVATE_KEY_PATH
  File "/home/richard/projects/HybridLogic/flocker/flocker/node/_deploy.py", line 15, in <module>
    from .gear import GearClient, PortMap, GearEnvironment
  File "/home/richard/projects/HybridLogic/flocker/flocker/node/gear.py", line 15, in <module>
    from treq import request, content
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/treq/__init__.py", line 3, in <module>
    from treq.api import head, get, post, put, patch, delete, request
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/treq/api.py", line 1, in <module>
    from twisted.web.client import Agent
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/web/client.py", line 765, in <module>
    from twisted.internet.ssl import (CertificateOptions,
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/internet/ssl.py", line 223, in <module>
    from twisted.internet._sslverify import (
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 184, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation()
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 159, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/service_identity/__init__.py", line 12, in <module>
    from . import pyopenssl
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/service_identity/pyopenssl.py", line 14, in <module>
    from ._common import (
  File "/home/richard/.virtualenvs/562/lib/python2.7/site-packages/service_identity/_common.py", line 136, in <module>
    @attributes(["pattern"], apply_with_init=False)
exceptions.TypeError: attributes() got an unexpected keyword argument 'apply_with_init'

flocker.node.test
-------------------------------------------------------------------------------
Ran 1 tests in 0.002s

Richard Wall: It shouldn't affect Linux users following our tutorial, because it installs it in a virtualenv, but I'm not sure about Mac users using Homebrew. What happens if they've got service_identity installed?

Itamar Turner-Trauring: we should switch to latest characteristic

Itamar Turner-Trauring: and, in general, we should be vendoring all dependencies

Itamar Turner-Trauring: or using minimal versions, not specific ones, when installing as normal package as opposed to virtualenv
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-688. You are welcome to file additional issues in GitHub if that's easier for you.
