### ISSUE TITLE
Intermittent test failure in flocker.node.functional.test_deploy.DeployerTests.test_environment

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#860]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-860

This failure occurred during a build of #859

http://build.clusterhq.com/builders/flocker-twisted-trunk/builds/2186/steps/trial/logs/problems

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/srv/buildslave/flocker-twisted-trunk/venv/lib/python2.7/site-packages/flocker/node/functional/test_deploy.py", line 119, in started
    contents = path.child(b'env').getContent()
  File "/srv/buildslave/flocker-twisted-trunk/venv/lib/python2.7/site-packages/twisted/python/filepath.py", line 287, in getContent
    fp = self.open()
  File "/srv/buildslave/flocker-twisted-trunk/venv/lib/python2.7/site-packages/twisted/python/filepath.py", line 828, in open
    return open(self.path, mode + 'b')
exceptions.IOError: [Errno 2] No such file or directory: '/srv/buildslave/flocker-twisted-trunk/tmp-2186/_trial_temp/flocker.node.functional.test_dep/DeployerTests/test_environment/G9FRAg/temp/cd4b6d52-f6ff-46e7-9c9e-f09729073ca1.193028193989/env'

flocker.node.functional.test_deploy.DeployerTests.test_environment
-------------------------------------------------------------------------------
Ran 562 tests in 186.098s

FAILED (errors=1, successes=561)
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-860. You are welcome to file additional issues in GitHub if that's easier for you.
