### ISSUE TITLE
Some tests fail with unhelpful "exceptions.OSError: [Errno 2] No such file or directory" error message when binaries not on PATH

### ISSUE THREAD

**Issue by adamtheturtle** [ClusterHQ/flocker#883]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-883

My setup is the Flocker development Vagrant VM with a virtualenv in which I've run `pip install -e .[doc,dev]`

Running `sudo $(type -p trial) --temp=/tmp/trial flocker` is how I've been running the tests as root. This has numerous failures, one of which is `flocker.volume.functional.test_service.RealisticTests.test_handoff`. Running this test alone has the following unhelpful traceback:

```
Traceback (most recent call last):
  File "/home/vagrant/Envs/flocker-850/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/vagrant/flocker/volume/service.py", line 247, in push
    getting_snapshots = destination.snapshots(volume)
  File "/vagrant/flocker/volume/_ipc.py", line 112, in snapshots
    volume.name.to_bytes()]
  File "/vagrant/flocker/volume/testtools.py", line 114, in get_output
    return ProcessNode.get_output(self, self._mutate(remote_command))
  File "/vagrant/flocker/common/_ipc.py", line 86, in get_output
    tuple(map(self._quote, remote_command)))
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
exceptions.OSError: [Errno 2] No such file or directory

flocker.volume.functional.test_service.RealisticTests.test_handoff
```

Further inspection shows that this is because `flocker-volume` is not on `os.getenv("PATH")`. At least the error messages should say something like "flocker-volume not on path".

(noticed by Jean-Paul and Richard helped me look into it)

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-883. You are welcome to file additional issues in GitHub if that's easier for you.
