### ISSUE TITLE
Many tests fail

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#940]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-940

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/exarkun/Environments/flocker/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/home/exarkun/Environments/flocker/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/exarkun/Environments/flocker/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/exarkun/Projects/flocker/master/flocker/node/_docker.py", line 402, in _list
    for container_path, node_path in data[u"Volumes"].items():
exceptions.AttributeError: 'NoneType' object has no attribute 'items'

flocker.node.functional.test_deploy.DeployerTests.test_environment
flocker.node.functional.test_deploy.DeployerTests.test_links
flocker.node.functional.test_deploy.DeployerTests.test_restart
flocker.node.functional.test_docker.GenericDockerClientTests.test_add_starts_container
flocker.node.functional.test_docker.GenericDockerClientTests.test_add_with_port
flocker.node.functional.test_docker.GenericDockerClientTests.test_add_with_volumes
flocker.node.functional.test_docker.GenericDockerClientTests.test_container_name
flocker.node.functional.test_docker.GenericDockerClientTests.test_dead_is_listed
flocker.node.functional.test_docker.IDockerClientNamespacedTests.test_added_is_listed
flocker.node.functional.test_docker.IDockerClientNamespacedTests.test_container_name
flocker.node.functional.test_docker.IDockerClientNamespacedTests.test_removed_is_not_listed
flocker.node.functional.test_docker.IDockerClientTests.test_added_is_listed
flocker.node.functional.test_docker.IDockerClientTests.test_container_name
flocker.node.functional.test_docker.IDockerClientTests.test_removed_is_not_listed
flocker.node.functional.test_docker.NamespacedDockerClientTests.test_add_starts_container
flocker.node.functional.test_docker.NamespacedDockerClientTests.test_add_with_port
flocker.node.functional.test_docker.NamespacedDockerClientTests.test_add_with_volumes
flocker.node.functional.test_docker.NamespacedDockerClientTests.test_container_name
flocker.node.functional.test_docker.NamespacedDockerClientTests.test_dead_is_listed
flocker.node.functional.test_docker.NamespacedDockerClientTests.test_isolated_namespaces
-------------------------------------------------------------------------------
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-940. You are welcome to file additional issues in GitHub if that's easier for you.
