### ISSUE TITLE
'Bad exit', ['flocker-changestate' ...

### ISSUE THREAD

**Issue by sschwarz** [ClusterHQ/flocker#951]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-951

Hi, 

1) add application node, run flocker-deploy
2) remove application from that node, run flocker-deploy
3) add that application back on that node, run flocker-deploy ->ends with this error. If I manually delete ZFS volume before calling 3) , there is no problem, but, obviously, no data persistence... 
What am I doing wrong? Or is it some bug? 
I am testing flocker-deploy on my personal computer (debian), node is on same computer.
Files:
application.yml
```
"version": 1
"applications":
  "test":
    "image": "test"
    "ports":
    - "internal": 80
      "external": 8080
    "volume":
      "mountpoint": "/var/www/static/data"
```
deployment.yml in 1)
```
"version": 1
"nodes":
  "127.0.0.1": ['test']
```
deployment.yml in 2)
```
"version": 1
"nodes":
  "127.0.0.1": []
```
deployment.yml in 3)
```
"version": 1
"nodes":
  "127.0.0.1": ['test']
```

Whole error:
```
Unhandled Error
Traceback (most recent call last):
Failure: flocker.volume.filesystems.zfs.CommandFailed: 
main function encountered error
Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback (failure with no frames): <class 'flocker.volume.filesystems.zfs.CommandFailed'>: 
]]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
--- <exception caught here> ---
  File "/home/samuel/docker/flocker-tutorial/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/home/samuel/docker/flocker-tutorial/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/samuel/docker/flocker-tutorial/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/samuel/docker/flocker-tutorial/local/lib/python2.7/site-packages/flocker/common/_ipc.py", line 90, in get_output
    raise IOError("Bad exit", remote_command, e.returncode, e.output)
exceptions.IOError: ('Bad exit', ['flocker-changestate', '"version": 1\n"nodes":\n  "127.0.0.1": [\'test\']', '"version": 1\n"applications":\n  "test":\n    "image": "test"\n    "ports":\n    - "internal": 80\n      "external": 8080\n    "volume":\n      "mountpoint": "/var/www/static/data"', '127.0.0.1:\n  applications: {}\n  used_ports: [22, 25, 53, 80, 139, 445, 631, 9001, 9033, 33805, 33806, 33807, 33808,\n    33810, 33813, 33814, 33815, 38348, 38349, 44587, 44837, 45320, 45321, 45325, 45330,\n    45331, 47654, 48216, 48782, 50516, 51732, 51733, 51734, 51736, 51737, 51738, 51742,\n    51743, 51744, 51882, 52206, 53337, 54548, 55456, 56677, 58805, 59216, 59266, 59687,\n    59787]\n  version: 1\n', '127.0.0.1'], 1, '')
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-940. You are welcome to file additional issues in GitHub if that's easier for you.
