### ISSUE TITLE
Exception when moving volume - using flocker on ubuntu VMs

### ISSUE THREAD

**Issue by praveenj83** [ClusterHQ/flocker#972]
I installed flocker and its dependencies on 2 ubuntu VMs using virtualenv and pip. I also setup a zfs pool as mentioned in https://github.com/ClusterHQ/flocker/compare/fedora-20-install.

I was able to follow the tutorial up to the point of migrating a volume from one VM to another (I was able to access data in mongodb from either VM after deploying). When I tried to move the container with a volume attached to the second VM, I'm getting the following exception:

main function encountered error
Traceback (most recent call last):
File "/root/flocker/lib/python2.7/site-packages/flocker/common/script.py", line 137, in main
self.react(self.script.main, (options,), reactor=self._reactor)
File "/root/flocker/lib/python2.7/site-packages/twisted/internet/task.py", line 875, in react
finished = main(_reactor, *argv)
File "/root/flocker/lib/python2.7/site-packages/flocker/volume/service.py", line 449, in main
return self._volume_script.main(reactor, options, service)
File "/root/flocker/lib/python2.7/site-packages/flocker/volume/script.py", line 241, in main
return maybeDeferred(options.subOptions.run, service)
--- ---
File "/root/flocker/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
result = f(*args, **kw)
File "/root/flocker/lib/python2.7/site-packages/flocker/volume/script.py", line 123, in run
sys.stdin)
File "/root/flocker/lib/python2.7/site-packages/flocker/volume/service.py", line 303, in receive
raise ValueError()
exceptions.ValueError:
warning: cannot send 'flocker/c9af0114-64ce-49bb-aa5f-bba6da2ff0f2.default.mongodb-volume-example@b6950865-8bba-40cb-a9fa-3ca5bfe57540': Broken pipe
Unhandled Error
Traceback (most recent call last):
File "/root/flocker/lib/python2.7/site-packages/flocker/node/_deploy.py", line 251, in run
RemoteVolumeManager(destination))
File "/root/flocker/lib/python2.7/site-packages/flocker/volume/service.py", line 282, in push
pushing = getting_snapshots.addCallback(got_snapshots)
File "/root/flocker/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallback
callbackKeywords=kw)
File "/root/flocker/lib/python2.7/site-packages/twisted/internet/defer.py", line 295, in addCallbacks
self._runCallbacks()
--- ---
File "/root/flocker/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/root/flocker/lib/python2.7/site-packages/flocker/volume/service.py", line 280, in got_snapshots
receiver.write(chunk)
File "/usr/lib/python2.7/contextlib.py", line 35, in __exit
self.gen.throw(type, value, traceback)
File "/root/flocker/lib/python2.7/site-packages/flocker/common/ipc.py", line 80, in run
raise IOError("Bad exit", remote_command, exit_code)
exceptions.IOError: [Errno Bad exit] ['flocker-volume', '--config', '/etc/flocker/volume.json', 'receive', 'c9af0114-64ce-49bb-aa5f-bba6da2ff0f2', 'default.mongodb-volume-example']: 1
main function encountered error
Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: : [Errno Bad exit] ['flocker-volume', '--config', '/etc/flocker/volume.json', 'receive', 'c9af0114-64ce-49bb-aa5f-bba6da2ff0f2', 'default.mongodb-volume-example']: 1
/root/flocker/lib/python2.7/site-packages/flocker/node/deploy.py:251:run
/root/flocker/lib/python2.7/site-packages/flocker/volume/service.py:282:push
/root/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:306:addCallback
/root/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:295:addCallbacks
--- ---
/root/flocker/lib/python2.7/site-packages/twisted/internet/defer.py:577:_runCallbacks
/root/flocker/lib/python2.7/site-packages/flocker/volume/service.py:280:got_snapshots
/usr/lib/python2.7/contextlib.py:35:__exit
/root/flocker/lib/python2.7/site-packages/flocker/common/_ipc.py:80:run
]]

So, this is happening with flocker-volume when I run it with the volume-deployment-moved.yml from the tutorial. I understand that running flocker on ubuntu VMs is something you do not yet support, but any thoughts on what might be causing this will really help. Thanks a lot!

**Comment by binocarlos** [comment]
closing this issue now - please re-open this if it crops up in another form...
